- logfile: ""
- synopsisfile: ""
- topics:
  - topic1:
    - name: "/stereo/left/image_raw/compressed"
    - freq_mean: 10.0
    - freq_std_dev: 0.15

  - topic2:
    - name: "/stereo/right/image_raw/compressed"
    - freq_mean: 10.0
    - freq_std_dev: 0.15