bag_file: "/home/amrl-husky/Documents/datachecker/temp/test_bag.bag"
topics:
  left_image:
      name: "/stereo/left/image_raw/compressed"
      freq_mean: 10.0
      freq_std_dev: 0.15

  right_image:
      name: "/stereo/right/image_raw/compressed"
      freq_mean: 10.0
      freq_std_dev: 0.15

  vectornav_gps:
      name: "/vectornav/GPS"
      freq_mean: 20.0
      freq_std_dev: 0.15

  vectornav_imu:
      name: "/vectornav/IMU"
      freq_mean: 20.0
      freq_std_dev: 0.15

  vectornav_mag:
      name: "/vectornav/Mag"
      freq_mean: 20.0
      freq_std_dev: 0.15

  vectornav_odom:
      name: "/vectornav/Odom"
      freq_mean: 20.0
      freq_std_dev: 0.15